# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sait_\Desktop\Road_Pothole_Detection\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWin(object):
    def setupUi(self, mainWin):
        mainWin.setObjectName("mainWin")
        mainWin.setEnabled(True)
        mainWin.resize(991, 698)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWin.sizePolicy().hasHeightForWidth())
        mainWin.setSizePolicy(sizePolicy)
        mainWin.setMinimumSize(QtCore.QSize(100, 100))
        mainWin.setBaseSize(QtCore.QSize(100, 100))
        mainWin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(mainWin)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.oriImage = QtWidgets.QLabel(self.centralwidget)
        self.oriImage.setGeometry(QtCore.QRect(60, 30, 640, 360))
        self.oriImage.setMouseTracking(True)
        self.oriImage.setStyleSheet("background : grey\n"
"")
        self.oriImage.setText("")
        self.oriImage.setObjectName("oriImage")
        self.trackImage = QtWidgets.QLabel(self.centralwidget)
        self.trackImage.setGeometry(QtCore.QRect(730, 30, 200, 360))
        self.trackImage.setStyleSheet("background : grey\n"
"")
        self.trackImage.setText("")
        self.trackImage.setObjectName("trackImage")
        self.meshOnOff = QtWidgets.QPushButton(self.centralwidget)
        self.meshOnOff.setGeometry(QtCore.QRect(770, 430, 80, 21))
        self.meshOnOff.setObjectName("meshOnOff")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(60, 420, 411, 221))
        self.listView.setObjectName("listView")
        mainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 20))
        self.menubar.setObjectName("menubar")
        mainWin.setMenuBar(self.menubar)

        self.retranslateUi(mainWin)
        QtCore.QMetaObject.connectSlotsByName(mainWin)

    def retranslateUi(self, mainWin):
        _translate = QtCore.QCoreApplication.translate
        mainWin.setWindowTitle(_translate("mainWin", "main"))
        self.meshOnOff.setText(_translate("mainWin", "Mesh"))
